# Generated by Django 6.0.4 on 2026-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_category_alter_product_options_product_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Resim URL'),
        ),
    ]
